
name: Build and Deploy to GKE

on: push


env:
  IMAGE: cocoexplorer
  IMAGE_NAME: "gcr.io/$PROJECT_ID/$IMAGE-${GITHUB_REF##*/}:$GITHUB_SHA"

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: |-
        docker build \
          --file Dockerfile \
          --tag i008/cocoexplorer:latest \
        .

    - name: Publish
      run: |-
        docker push i008/cocoexplorer:latest
